project:
  type: website
  output-dir: docs
  resources:
    - assets/fungcv.pdf

website:
  title: "juanfung.github.io"
  favicon: favicon.ico
  page-footer: "Last updated 2025-01-24"
  open-graph: true
  google-analytics:
    tracking-id: "G-F3WYV37Y07"
    anonymize-ip: true
    google-site-verification: "kwzbfvt2mnY8pb5FlOEpXM8GxspKn1EvsyEF69XXDu4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - href: assets/fungcv.pdf
        text: CV

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full



