project:
  type: website
  resources:
    - assets/fungcv.pdf

website:
  title: "juanfung.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - href: fungcv.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



